fixed issue with animation
OleksiiKolomiiets/DataStructuresMemories pull request #6
Opened 2018-04-20 09:35 UTC by OleksiiKolomiiets

2018-04-23 15:15 UTC, AlexeyTyurenkov requested changes

2018-04-23 15:15 UTC, AlexeyTyurenkov commented on DataStructuresMemories/Models/DataSourceModel.swift
> +let dataStructLinksSource: [String] = [
OMG

2018-04-23 15:15 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +            case .WKWebView:
Is there a better way to do it?

2018-04-23 15:15 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +                guard let targetController = mainStoryboard.instantiateViewController(withIdentifier: type.rawValue) as? WKWebViewController else { return }
I guess we have to use protocols here

2018-04-23 15:15 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +func someFunc() {
WTF?

2018-04-23 15:15 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/WKWebViewController.swift
> +    override func loadView() {
hmmm not sure

2018-04-23 15:32 UTC, OleksiiKolomiiets commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +func someFunc() {
I will fixed it.

2018-04-23 15:34 UTC, OleksiiKolomiiets commented on DataStructuresMemories/Models/DataSourceModel.swift
> +let dataStructLinksSource: [String] = [
I will fixed it.

2018-04-23 16:06 UTC, OleksiiKolomiiets commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +                guard let targetController = mainStoryboard.instantiateViewController(withIdentifier: type.rawValue) as? WKWebViewController else { return }
Ok.

2018-04-23 16:23 UTC, OleksiiKolomiiets commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +            case .WKWebView:
Yes, I will fixed it)

2018-04-23 16:24 UTC, OleksiiKolomiiets commented on DataStructuresMemories/ViewControllers/WKWebViewController.swift
> +    override func loadView() {
It works. I will look for a better approach.

2018-04-24 15:36 UTC, AlexeyTyurenkov approved these changes

2018-04-24 15:36 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/URLPresenter.swift
> +                controller.navigationController?.present(targetController as! UIViewController, animated: true)
Why do you use force unwrap here?

2018-04-24 15:36 UTC, AlexeyTyurenkov commented on DataStructuresMemories/ViewControllers/WebPresenters/SFSafaryPresenter.swift
> +            let safariVC = SFSafariViewController(url: url, entersReaderIfAvailable: false)
why do you implement in this way?

2018-04-24 15:37 UTC, merged